ARG osVersion
FROM mcr.microsoft.com/windows/servercore:$osVersion
RUN cmd /c @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
RUN choco install git --version 2.22.0 -y
RUN choco install openjdk --version 11.0.2.01 -y
RUN cmd /c rmdir /q /s %USERPROFILE%\AppData\Local\Temp\chocolatey
COPY target/*.jar C:/k8s-helper/
COPY target/lib/*.jar C:/k8s-helper/
